sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5tDrtkhXqvt3yYqk85DP
    access-key-secret: GVYqXrbuMpHKtwJTucG4tWHkWay6St
    bucket-name: java190lz
    endpoint: oss-cn-guangzhou.aliyuncs.com
